<div class="row">
    <?php
    foreach ($products as $product) {
        echo '<div class="col-5 my-2">
                <div class="card">
                    <div class="card-body">
                    <h5 class="card-title">' . $product->name . '</h5>
                    <h6 class="card-subtitle mb-2 text-muted">' . $product->category . '</h6>
                    <p class="card-text">Price : ' . $product->price . ' Stock : ' . $product->stock . '</p>
                    <a href="#" class="card-link btn btn-info ' . (($product->stock <= 0) ? 'disabled' : '') . '">Add to cart</a>
                    </div>
                </div>
            </div>';
    } ?>
</div>