<div class="overfloe-hidden w-50 justify-content-center">
    <div class="row text-break alert alert-info">
        <?php echo $this->getContent(); ?>
    </div>
    <div class="row">
        <form method="post">
            <fieldset>
                <!-- Form Name -->
                <legend class="h1 text-warning">Place Order</legend>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="name">Product Id</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "product_id",
                            "class" => "form-control input-md readonly",
                            "value" =>$product_id
                        ]); ?>
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="customer_name">Customer Name</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "customer_name",
                            "placeholder" => "CUSTOMER NAME",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="price">Quantity</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "quantity",
                            "placeholder" => "PRODUCT QUANTITY",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div><!-- Text input-->
                <!-- Button -->
                <div class="form-group">
                    <div class="">
                        <?php echo $this->tag->submitButton([
                            'Place Order',
                            "class" => "btn btn-primary"
                        ]); ?>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>