<div class="overfloe-hidden w-50 justify-content-center">
    <div class="row text-break alert alert-info">
        <?php echo $this->getContent(); ?>
    </div>
    <div class="row">
        <form method="post">
            <fieldset>
                <!-- Form Name -->
                <legend class="h1 text-warning">Add New Product</legend>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="name">Product NAME</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "name",
                            "placeholder" => "PRODUCT NAME",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="category">Category</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "category",
                            "placeholder" => "PRODUCT CATEGORY",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="price">Price</label>
                    <div class="">
                        <?php echo $this->tag->textField([
                            "price",
                            "placeholder" => "PRICE",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="stock">Stock</label>
                    <div class="">
                    <?php echo $this->tag->textField([
                            "stock",
                            "placeholder" => "STOCK",
                            "class" => "form-control input-md",
                        ]); ?>
                    </div>
                </div><!-- Text input-->
                <!-- Button -->
                <div class="form-group">
                    <div class="">
                        <?php echo $this->tag->submitButton([
                            'Add Product',
                            "class" => "btn btn-primary"
                        ]); ?>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>