<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Product ID</th>
            <th scope="col">Quantity</th>
            <th scope="col">Customer name</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->session->user)) {
            foreach ($orders as $k => $order) {
                echo '<tr>
                <th scope="row">' . $k . '</th>
                <td>' . $order->name . '</td>
                <td>' . $order->product_id . '</td>
                <td>' . $order->quantity . '</td>
                <td>' . $order->customer_name . '</td>
                <td>' . $order->status . '</td>
            </tr>';
            }
        }
        ?>

    </tbody>
</table>